export const VIA_ABBREVIATIONS: Record<string, string> = {
  av: "Avenida",
  avda: "Avenida",
  "av.": "Avenida",
  pje: "Pasaje",
  psje: "Pasaje",
  pj: "Pasaje",
  p: "Pasaje",
  cl: "Calle",
  c: "Calle",
  "c/": "Calle",
  "cl.": "Calle",
  cmno: "Camino",
  cam: "Camino",
  "cam.": "Camino",
  crta: "Carretera",
  ctra: "Carretera",
  "crta.": "Carretera",
  "ctra.": "Carretera",
  blvr: "Boulevard",
  blvd: "Boulevard",
  pas: "Pasaje",
  pasaje: "Pasaje",
  calle: "Calle",
  avenida: "Avenida",
  camino: "Camino",
  carretera: "Carretera",
  boulevard: "Boulevard",
  rotonda: "Rotonda",
  puente: "Puente",
  "ruta 5": "Ruta 5",
  "ruta 5 norte": "Ruta 5 Norte",
  "ruta 5 sur": "Ruta 5 Sur",
  panamericana: "Ruta 5",
  "panamericana norte": "Ruta 5 Norte",
  "panamericana sur": "Ruta 5 Sur",
};

export const UNIT_ABBREVIATIONS: Record<string, string> = {
  dpto: "Departamento",
  depto: "Departamento",
  dep: "Departamento",
  of: "Oficina",
  ofi: "Oficina",
  int: "Interior",
  loc: "Local",
  mz: "Manzana",
  manz: "Manzana",
  pobl: "Población",
  villa: "Villa",
  km: "Kilómetro",
  "km.": "Kilómetro",
  block: "Block",
  blck: "Block",
  casa: "Casa",
  sitio: "Sitio",
  lote: "Lote",
  lt: "Lote",
  fundo: "Fundo",
  condominio: "Condominio",
  cond: "Condominio",
  edificio: "Edificio",
  edif: "Edificio",
  ed: "Edificio",
  torre: "Torre",
  piso: "Piso",
  dept: "Departamento",
};

export const NUMBER_PREFIXES: string[] = ["N°", "Nº", "No", "Nro", "Núm", "Nro.", "Núm.", "#"];

export const SINALNUMERO: string[] = ["S/N", "s/n", "SN", "sn", "Sin Numero", "Sin número", "sin numero", "sin número"];

export const COMUNA_ABBREVIATIONS: Record<string, string> = {
  stgo: "Santiago",
  "stgo.": "Santiago",
  "santiago centro": "Santiago",
  centro: "Santiago",
  vdm: "Viña del Mar",
  "v.d.mar": "Viña del Mar",
  viña: "Viña del Mar",
  vina: "Viña del Mar",
  vap: "Valparaíso",
  valpo: "Valparaíso",
  pdtehurtado: "Padre Hurtado",
  "pdte hurtado": "Padre Hurtado",
  snbdo: "San Bernardo",
  "s.bernardo": "San Bernardo",
  sanbernardo: "San Bernardo",
  conce: "Concepción",
  concepc: "Concepción",
  ptomontt: "Puerto Montt",
  "pto montt": "Puerto Montt",
  ptaarenas: "Punta Arenas",
  "pta arenas": "Punta Arenas",
  maipu: "Maipú",
  nunoa: "Ñuñoa",
  penalolen: "Peñalolén",
  conchali: "Conchalí",
  sanjose: "San José de Maipo",
  chillan: "Chillán",
  "chillan viejo": "Chillán Viejo",
  lascondes: "Las Condes",
  lareina: "La Reina",
  laflorida: "La Florida",
  lapintana: "La Pintana",
  lagranja: "La Granja",
  macul: "Macul",
  providencia: "Providencia",
  vitacura: "Vitacura",
  lobarnechea: "Lo Barnechea",
  loprado: "Lo Prado",
  loespejo: "Lo Espejo",
  lacisterna: "La Cisterna",
  quintanormal: "Quinta Normal",
  recoleta: "Recoleta",
  renca: "Renca",
  quilicura: "Quilicura",
  huechuraba: "Huechuraba",
  independencia: "Independencia",
  cerrillos: "Cerrillos",
  cerronav: "Cerro Navia",
  estacioncentral: "Estación Central",
  pudahuel: "Pudahuel",
  maipú: "Maipú",
  puentealto: "Puente Alto",
  sanmiguel: "San Miguel",
  sanramon: "San Ramón",
  sanjoaquin: "San Joaquín",
  pedroaguirrecerda: "Pedro Aguirre Cerda",
  pac: "Pedro Aguirre Cerda",
  talagante: "Talagante",
  penaflor: "Peñaflor",
  melipilla: "Melipilla",
  curacavi: "Curacaví",
  mariapinto: "María Pinto",
  buin: "Buin",
  paine: "Paine",
  colina: "Colina",
  lampa: "Lampa",
  tiltil: "Tiltil",
  pirque: "Pirque",
  caleradetango: "Calera de Tango",
  elmonte: "El Monte",
  islademaipo: "Isla de Maipo",
  alhue: "Alhué",
  sanpedro: "San Pedro",
  sanjosedemaipo: "San José de Maipo",
};

export const PHONE_REGEX = /(?:\+56\s?)?(?:9\s?\d{4}\s?\d{4}|2\s?\d{7}|3\d\s?\d{7})/g;

export const RUT_REGEX = /\d{1,2}\.?\d{3}\.?\d{3}[\-]?\d{1}[Kk0-9]/g;

export const EMAIL_REGEX = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g;

export const BUILDING_PREFIXES = ["edif", "ed", "edificio", "torre", "condominio", "cond"];

export const VILLA_PREFIXES = ["villa", "población", "pobl", "poblacion", "condominio"];

export const FUNDO_PREFIXES = ["fundo", "parcela", "sitio", "lote", "hijuela"];

export const INTERSECTION_KEYWORDS = ["esq", "esquina", "c/", "con", "y"];

export const KM_KEYWORDS = ["km", "kilómetro", "kilometro"];
